# databases — это отдельный раздел верхнего уровня для баз данных
databases:
  - name: beautybook-db
    databaseName: beautybook
    user: beautybook_user

services:
  # Redis также является сервисом
  - type: redis
    name: beautybook-redis
  
  # Веб-сервис, который запускает ваш код
  - type: web
    name: beautybook-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT beautybook.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 # Убедитесь, что это ваша версия Python
      - key: SECRET_KEY
        generateValue: true
      # Передаем URL базы данных и Redis в наше приложение
      - key: DATABASE_URL
        fromDatabase:
          name: beautybook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: beautybook-redis
          property: connectionString
