services:
  # 1. Веб-сервис (Daphne для Django)
  - type: web
    name: beautybook-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT beautybook.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 # Убедитесь, что это ваша версия Python
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  # 2. База данных PostgreSQL
  - type: psql # <--- ЭТО ПРАВИЛЬНОЕ ЗНАЧЕНИЕ
    name: beautybook-db
    ipAllowList: []

  # 3. Сервис Redis
  - type: redis
    name: beautybook-redis
    ipAllowList: []
